### ISSUE TITLE
在胡牌时，如果有红宝牌，番种会少计算一番

### ISSUE THREAD

**Issue by minerva0394** [linlexiao0/mahjong-vue#2]
rt，如果在胡牌的时候，刚好带了AkaDora，calc.js方法中，少了对AkaDora的计算
![01e9f1dd7e76affdcf46d6a3f90c551](https://github.com/linlexiao0/mahjong-vue/assets/58332372/e33ab0c7-d960-4c17-b988-f9a457305144)

**Comment by minerva0394** [comment]
解决了
![image](https://github.com/linlexiao0/mahjong-vue/assets/58332372/3b36cfe8-2e46-4e85-a827-ca95c17caadb)

**Comment by llx07** [comment]
已修复
